### ISSUE TITLE
Filter not working correctly on `strftime`

### ISSUE THREAD

**Issue by mashton** [amyxzhang/policykit#362]
This passes the [filter](https://github.com/amyxzhang/policykit/blob/master/policykit/policyengine/filter.py):

```python
closing_at = (action.proposal.proposal_time + datetime.timedelta(days=3)).strftime("%Y-%m-%d")
```

This does not:

```python
closing_at_dt = action.proposal.proposal_time + datetime.timedelta(days=3)
closing_at = closing_at_dt.strftime("%Y-%m-%d")
```
Error produced is
```
Filter errors: [{'type': 'filter', 'lineno': 8, 'code': 'closing_at_dt.strftime',
'message': 'function cannot be called because it is not in the list of whitelisted module functions.'}]
```

**Bug**: Inconsistent filter results based on whether an intermediate variable is used or not

`strftime` should be permitted, because the above example will be common for passing params to metagov. Both the 2 examples should work.

**Comment by rickygv99** [comment]
To fix the code filtering problem with intermediate variables / importing libraries, one approach we could take is to implement a wrapper library for each library that we import. For example, instead of allowing users to import the `requests` library, we would implement a wrapper class `policykit.requests` which wraps only the safe function calls from `requests` and doesn't wrap any dangerous function calls. We can then pre-import `policykit.requests` and have it available to users in their coding environment. Users would not be allowed to import their own libraries not included in our wrappers (e.g. cannot import requests, etc.).

For example, suppose library `A` has functions x(), y() and z(). Functions x() and y() are harmless but function z() is potentially dangerous. We can create a library `policykit.A` which wraps library `A` as so:

```
class policykit.A:
  def x():
    from A import x as x2
    x2()

  def y():
    from A import y as y2
    y2()

  # We don't wrap z() because we don't want the user to be able to call z()
```

**Comment by mashton** [comment]
closing in favor of https://github.com/amyxzhang/policykit/issues/513
