### ISSUE TITLE
Add documentation about editor / available libraries / variables to wiki

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/policykit#66]
could be listed to the side of the code editor

**Comment by rickygv99** [comment]
Since the editor now displays real-time filtering errors if the user attempts to import a model that isn't whitelisted, I think that this would be better suited for a wiki/doc (on GitHub maybe? and we can link to it) than on the editor itself -- especially since we whitelist individual functions within a model as well and displaying all individual whitelisted functions to the user would be too much information.
